# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CmdGenie < Formula
  desc "CLI app to suggest prompted commands"
  homepage "https://github.com/the-Jinxist/cmd_genie"
  version "0.4.3"

  on_macos do
    on_intel do
      url "https://github.com/the-Jinxist/cmd_genie/releases/download/v0.4.3/cmd_genie_Darwin_x86_64.tar.gz"
      sha256 "1c00f4a28e95dd9d307de33f6b2a9b8d5ee20e054da574ac9c0d51b1c8b025ba"

      def install
        bin.install "cmd_genie"
      end
    end
    on_arm do
      url "https://github.com/the-Jinxist/cmd_genie/releases/download/v0.4.3/cmd_genie_Darwin_arm64.tar.gz"
      sha256 "03c1cdb4de883a0eb1202f3a71234e870e7ceacb2eaa06ab4d35373cb58eabbd"

      def install
        bin.install "cmd_genie"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/the-Jinxist/cmd_genie/releases/download/v0.4.3/cmd_genie_Linux_x86_64.tar.gz"
        sha256 "f253e0c4e1fc1c31c3e5f443f8ef86e530b5bad8a4f4a24154193b089a0847cd"

        def install
          bin.install "cmd_genie"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/the-Jinxist/cmd_genie/releases/download/v0.4.3/cmd_genie_Linux_arm64.tar.gz"
        sha256 "aa9af6244ab2aecf2ecec9d2bf162a7b83b48cf4e3fd3ca0bd886d5c04849b8d"

        def install
          bin.install "cmd_genie"
        end
      end
    end
  end

  def post_install
    cmd_genie --help
  end
end
